SELECT AUTHOR_ID
     , AUTHOR_NAME
     , CATEGORY
     , SUM(PRICE * SALES) 'TOTAL_SALES'
  FROM BOOK A
 INNER JOIN AUTHOR B USING(AUTHOR_ID)
 INNER JOIN BOOK_SALES C USING(BOOK_ID)
 WHERE LEFT(SALES_DATE, 7) = '2022-01'
 GROUP BY 1, 3
 ORDER BY 1, 3 DESC