SELECT B.USER_ID
     , B.NICKNAME
     , CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) '전체주소'
     , CONCAT(SUBSTRING(B.TLNO FROM 1 FOR 3), '-'
            , SUBSTRING(B.TLNO FROM 4 FOR 4), '-'
            , SUBSTRING(B.TLNO FROM 8 FOR 4)) '전화번호'
  FROM USED_GOODS_BOARD A
  JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
 GROUP BY B.USER_ID
HAVING COUNT(BOARD_ID) >= 3
 ORDER BY 1 DESC