SELECT REST_ID,
       REST_NAME,
       FOOD_TYPE,
       FAVORITES,
       ADDRESS,
       ROUND(AVG(REVIEW_SCORE), 2) 'SCORE'
  FROM REST_INFO A
  JOIN REST_REVIEW B USING (REST_ID)
 WHERE ADDRESS LIKE '서울%'
 GROUP BY 1
 ORDER BY 6 DESC, 4 DESC