SELECT A.CAR_ID, ROUND(AVG(A.DURATION), 1) 'AVERAGE_DURATION'
  FROM (SELECT HISTORY_ID, CAR_ID, DATEDIFF(IFNULL(END_DATE, NOW()), START_DATE) + 1 'DURATION'
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A
 GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
 ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC