SELECT A.*
     , ROUND(PURCHASED_USERS / TOTAL_USERS, 1) 'PURCHASED_RATIO'
  FROM (
        SELECT YEAR(SALES_DATE) 'YEAR'
             , MONTH(SALES_DATE) 'MONTH'
             , COUNT(DISTINCT USER_ID) 'PURCHASED_USERS'
          FROM USER_INFO
          JOIN ONLINE_SALE USING (USER_ID)
         WHERE YEAR(JOINED) = '2021'
         GROUP BY YEAR, MONTH
       ) A
     , (
        SELECT COUNT(USER_ID) 'TOTAL_USERS'
          FROM USER_INFO
         WHERE YEAR(JOINED) = '2021'
       ) B
 GROUP BY YEAR, MONTH
 ORDER BY YEAR, MONTH