SELECT PRODUCT_ID
     , PRODUCT_NAME
     , SUM(PRICE * AMOUNT) 'TOTAL_SALES'
  FROM FOOD_PRODUCT
  JOIN FOOD_ORDER USING(PRODUCT_ID)
 WHERE YEAR(PRODUCE_DATE) = 2022
   AND MONTH(PRODUCE_DATE) = 5
 GROUP BY 1
 ORDER BY 3 DESC, 1