SELECT FLAVOR
  FROM (
        SELECT FLAVOR
             , SUM(TOTAL_ORDER) 'TOTAL_ORDER'
          FROM FIRST_HALF
         GROUP BY FLAVOR
       ) A
  JOIN (
        SELECT FLAVOR
             , SUM(TOTAL_ORDER) 'TOTAL_ORDER'
          FROM JULY
         GROUP BY FLAVOR
       ) B USING (FLAVOR)
 GROUP BY FLAVOR
 ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
 LIMIT 3