WITH RECURSIVE TIMETABLE (HOUR) AS (
    SELECT 0
    UNION
    SELECT HOUR + 1 FROM TIMETABLE WHERE HOUR < 23
)

SELECT HOUR
     , COUNT(ANIMAL_ID) 'COUNT'
  FROM TIMETABLE A
  LEFT JOIN ANIMAL_OUTS B
    ON A.HOUR = HOUR(B.DATETIME)
 GROUP BY HOUR
 ORDER BY 1