SELECT B.USER_ID
     , B.NICKNAME
     , SUM(PRICE) 'TOTAL_SALES'
  FROM USED_GOODS_BOARD A
  JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
 WHERE STATUS = 'DONE'
 GROUP BY B.USER_ID
HAVING SUM(PRICE) >= 700000
 ORDER BY 3