SELECT A.ITEM_ID
     , B.ITEM_NAME
     , B.RARITY
  FROM ITEM_TREE A
  JOIN ITEM_INFO B ON A.ITEM_ID = B.ITEM_ID
  JOIN ITEM_INFO C ON A.PARENT_ITEM_ID = C.ITEM_ID
 WHERE A.PARENT_ITEM_ID IS NOT NULL
   AND C.RARITY = 'RARE'
 ORDER BY B.ITEM_ID DESC