SELECT ID
     , FISH_NAME
     , A.LENGTH
  FROM (
        SELECT FISH_NAME
             , MAX(LENGTH) 'LENGTH'
             , FISH_TYPE
          FROM FISH_INFO
          JOIN FISH_NAME_INFO USING (FISH_TYPE)
         GROUP BY FISH_NAME, FISH_TYPE
       ) A
  JOIN FISH_INFO B
    ON A.FISH_TYPE = B.FISH_TYPE
 WHERE A.LENGTH = B.LENGTH
 ORDER BY 1