SELECT SUM(SCORE) 'SCORE'
     , B.EMP_NO
     , EMP_NAME
     , POSITION
     , EMAIL
  FROM HR_DEPARTMENT A
  JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
  JOIN HR_GRADE C ON B.EMP_NO = C.EMP_NO
 GROUP BY B.EMP_NO
 ORDER BY SCORE DESC
 LIMIT 1