SELECT CATEGORY
     , PRICE 'MAX_PRICE'
     , PRODUCT_NAME
  FROM (
        SELECT *
             , ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) 'ROW_NUM'
          FROM FOOD_PRODUCT
         WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
       ) A
 WHERE ROW_NUM = 1
 ORDER BY 2 DESC